version: "3"

services:

  spring-petclinic:
    build: .
    command: ["java","-jar", "-Dspring.profiles.active=mysql","/app.jar"]
    ports:
      - "8080:8080"
    environment:
      - MYSQL_URL=jdbc:mysql://mysql:3306/petclinic
      - MYSQL_PASS=petclinic
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
