version: "3"

services:

  spring-petclinic:
    build: .
    command: ["java","-javaagent:./monitoring/jmx_prometheus_javaagent-0.20.0.jar=1234:monitoring/config.yaml", "-jar","-Dspring.profiles.active=mysql","/app.jar"]
    ports:
      - "8080:8080"
      - "1234:1234"
    environment:
      - MYSQL_URL=jdbc:mysql://mysql:3306/petclinic
      - MYSQL_PASS=petclinic
    depends_on:
      mysql:
        condition: service_healthy
    container_name: spring-petclinic
    profiles: 
      - app

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    container_name: mysql
    profiles:
      - mysql
      - app

  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
      - postgres

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./monitoring:/etc/prometheus
    depends_on:
      - spring-petclinic
    profiles: 
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    profiles: 
      - monitoring
